// Split out of Sidebar.jsx — Vite's Fast Refresh warns/invalidates when a
// component file also exports a plain constant, so this map (used by both
// Sidebar and App) lives in its own module instead.
export const TAB_MODULE_KEY = {
  global_dashboard: "global_dashboard",
  approvals: "inbox",
  approvals__orders: "order",
  approvals__intake: "intake",
  approvals__payments: "payment_request",
  master_data__vendor:   "master_data_vendor",
  master_data__products: "master_data_products",
  master_data__orders:   "master_data_orders_tab",
  master_data__intakes:  "master_data_intakes",
  master_data__clauses:  "master_data_clauses",
  audit: "audit",
  proc_setup__vendor_list: "vendor_list",
  proc_setup__item_list: "item_list",
  proc_setup__category_list: "category_list",
  proc_setup__uom: "uom",
  proc_setup__term_condition: "term_condition",
  proc_setup__payment_terms: "payment_terms",
  proc_setup__payment_clauses: "payment_terms",
  proc_setup__government_laws: "government_laws",
  proc_setup__annexure: "annexure",
  dashboard: "dashboard",
  view_3d: "view_3d",
  procurement__intake: "intake",
  procurement__orders: "order",
  inventory__received_material_grn: "received_record",
  inventory__stock_inventory: "stock_available",
  inventory__material_issue: "consumption_record",
  operations__work_activity: "execution_plan",
  operations__staff_attendance: "staff_attendance",
  operations__manpower: "daily_manpower",
  finance__payment_request: "payment_request",
  finance__site_expense: "site_expense",
  finance__petty_cash: "petty_cash",
  finance__bills_documents: "bills_docs",
  confidential__loa: "loa",
  confidential__boq: "boq",
  confidential__drawings: "drawings",
  confidential__ra_bills: "ra_bills",
};
